documentation_source: nbs
output_folder: docs
notebook_processors: [
    nbquarto.processors:AutoDocProcessor,
]

processor_args:
  AutoDocProcessor: 
      repo_owner: muellerzr
      repo_name: nbquarto