project:
  type: website
  output-dir: ../_docs

website:
  sidebar:
    search: true
    contents:
      - index.qmd
      - getting_started.qmd
      - section: "Package Reference"
        contents: package_reference/*

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 4
    title-block-banner: true
