project:
  type: website
  output-dir: ../_docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Package Reference"
        contents: package_reference/*

format:
  html:
    theme: 
      - cosmo
    toc: true
    toc-depth: 4
