project:
  type: website
  output-dir: ../_docs

website:
  sidebar:
    search: true
    contents: auto
  margin-header: |
    ![](/logo.png)
  favicon: /logo.png
  repo-url: https://github.com/muellerzr/nbquarto
  issue-url: https://github.com/muellerzr/nbquarto/issues/new
  repo-actions: [edit, issue]
  page-navigation: true

  page-footer: 
    right:
      - icon: github
        href: https://github.com/muellerzr/nbquarto
        aria-label: nbquarto GitHub
  navbar:
    tools:
      - icon: github
        href: https://github.com/muellerzr/nbquarto
        aria-label: nbquarto GitHub

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    toc-depth: 4
    title-block-banner: true
