name: Upload Docs

on: 
  workflow_dispatch:

jobs:
  build-main-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:      
        ref: main
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        pip install -e .[quality]
        pip install git+https://github.com/huggingface/doc-builder
    - name: Build docs
      run: nbquarto-process --config_file config.yaml --notebook_folder nbs
    - name: Install quarto and jupyter
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.deb
        sudo dpkg -i quarto-1.3.361-linux-amd64.deb
        pip install notebook nbclient
    - name: Build docs with Quarto
      run: |
        cd docs
        quarto render
        cd ..
        zip -r main.zip _docs/ 
    - name: Upload to branch
      run: |
        curl -L \
          -X PUT \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -H "X-Github-Api-Version: 2022-11-28" \
          https://api.github.com/repos/muellerzr/nbquarto/contents/main.zip \
          -d '{"message": "Uploading updated docs from branch main", "content": "$(base64 main.zip)", "branch": "release-docs"}' 
